In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import seaborn as sns
import scipy.stats as stats
import plotly.express as px

url = "https://raw.githubusercontent.com/Belphegorus86/Gacha-Analyse-them-all-Mid-Project-Ironhack/main/CSV/Gacha_Data_Final.csv"
df = pd.read_csv(url)
df

,Index,Game,Region,Downloads 03/2023,Revenue 03/2023,Downloads 04/2023,Revenue 04/2023,Downloads 05/2023,Revenue 05/2023,Downloads 06/2023,...,Downloads 01/2024,Revenue 01/2024,Downloads 02/2024,Revenue 02/2024,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32
0,1,Genshin Impact,US,"2,800,000","34,000,000","2,900,000","48,000,000","3,000,000","45,000,000","2,700,000",...,"2,700,000","36,000,000","2,600,000","32,000,000",NaN,NaN,NaN,NaN,NaN,NaN
1,2,Honkai Star Rail,US,"6,000,000","82,000,000","11,000,000","23,000,000","5,000,000","43,000,000","1,700,000",...,"1,300,000","20,000,000","1,400,00","30,000,000",NaN,NaN,NaN,NaN,NaN,NaN
2,3,Honkai Star Rail,CN,"1,000,000","57,000,000","800,000","52,000,000","650,000","46,000,000","500,000",...,"300,000","10,000,000","300,000","22,000,000",NaN,NaN,NaN,NaN,NaN,NaN
3,4,Genshin Impact,CN,"600,000","23,000,000","700,000","46,000,000","700,000","44,000,000","700,000",...,"600,000","23,000,000","700,000","21,000,000",NaN,NaN,NaN,NaN,NaN,NaN
4,5,Uma Musume,JP,"50,000","27,000,000","50,000","23,000,000","80,000","74,000,000","30,000",...,"40,000","21,000,000","600,000","20,000,000",NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,103,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
df = df.drop(['Index', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32'], axis=1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Game               92 non-null     object
 1   Region             92 non-null     object
 2   Downloads 03/2023  90 non-null     object
 3   Revenue 03/2023    92 non-null     object
 4   Downloads 04/2023  92 non-null     object
 5   Revenue 04/2023    91 non-null     object
 6   Downloads 05/2023  88 non-null     object
 7   Revenue 05/2023    88 non-null     object
 8   Downloads 06/2023  92 non-null     object
 9   Revenue 06/2023    92 non-null     object
 10  Downloads 07/2023  92 non-null     object
 11  Revenue 07/2023    92 non-null     object
 12  Downloads 08/2023  92 non-null     object
 13  Revenue 08/2023    92 non-null     object
 14  Downloads 09/2023  92 non-null     object
 15  Revenue 09/2023    92 non-null     object
 16  Downloads 10/2023  92 non-null     object
 17  Revenue 10/2023    92 non-null     object
 18  Downloads 11/2023  92 non-null     object
 19  Revenue 11/2023    92 non-null     object
 20  Downloads 12/2023  87 non-null     object
 21  Revenue 12/2023    87 non-null     object
 22  Downloads 01/2024  91 non-null     object
 23  Revenue 01/2024    91 non-null     object
 24  Downloads 02/2024  89 non-null     object
 25  Revenue 02/2024    89 non-null     object
dtypes: object(26)
memory usage: 21.3+ KB

In [3]:
column_data = df['Game'].tolist()
column_data

['Genshin Impact',
 'Honkai Star Rail',
 'Honkai Star Rail',
 'Genshin Impact',
 'Uma Musume',
 'FGO',
 'Heaven Burns Red',
 'Blue Archive',
 'NIKKE',
 'Diablo Immoral',
 'Memento Mori',
 'Blue Archive',
 'Project Sekai',
 'FGO',
 'Fire Emblem Heroes',
 'Arknights',
 'Epic Seven',
 'Princess Connect',
 'FF7',
 'Atelier Resleriana',
 'IM@S Deresute',
 'Azur Lane',
 'Shironeko Project',
 'Azur Lane',
 'Arknights',
 'Bang Dream',
 'IM@S Mirishita',
 'Project Sekai',
 'Punishing Gray Raven',
 'Limbus Company',
 'Atelier Resleriana',
 'BrownDust2',
 'FF7',
 'World Dai Star',
 'Idoly Pride',
 'Tower of Fantasy',
 'Dolphin Wave',
 'Honkai 3rd',
 'Utawarerumono',
 'Assault Lily',
 'Counterside',
 'Reverse 1999',
 'Aether Gazer',
 'Eversoul',
 'Honkai 3rd',
 'Reverse 1999',
 'Towatsugai',
 'Tears of Themis',
 'Snowbreak',
 'Magia Record',
 'Touhou Gensou Eclipse',
 'Punishing Gray Raven',
 'Guardian Tales',
 'D4DJ',
 'Guardian Tales',
 'IM@S Shinymas',
 'Revue Starlight',
 'Blue Reflection Sun',
 'Shironeko Golf',
 'Neural Cloud',
 'Neural Cloud',
 'Girls Frontline',
 'Girls Frontline',
 'D4DJ',
 'LL SF 2',
 'Higan Eruthyll',
 'Neural Cloud',
 'Artery Gear',
 'World Flipper',
 'Idoly Pride',
 'Takt op',
 'Artery Gear',
 'Takt op',
 'LL SIF 2',
 'Alice Fiction',
 'Nier Reincarnation',
 'Nier Reincarnation',
 'Engage Kill',
 'World Flipper',
 '404',
 'Sinoalice',
 'Sinoalice',
 'IM@S saisuta',
 'LL SIFAS',
 'Princess Connect',
 'Revived Witch',
 'LL SIF',
 'Counterside',
 'IM@S Deremas',
 'Warau Arsnotoria',
 'IM@S SideM',
 'Dragalia Lost',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan]

In [4]:
values_to_remove = ['Princess Connect', 'Revived Witch', 'LL SIF', 'Counterside', 'IM@S Deremas', 'Warau Arsnotoria', 'IM@S SideM', 'Dragalia Lost', np.nan]
df = df[~df['Game'].isin(values_to_remove)]
df

,Game,Region,Downloads 03/2023,Revenue 03/2023,Downloads 04/2023,Revenue 04/2023,Downloads 05/2023,Revenue 05/2023,Downloads 06/2023,Revenue 06/2023,...,Downloads 10/2023,Revenue 10/2023,Downloads 11/2023,Revenue 11/2023,Downloads 12/2023,Revenue 12/2023,Downloads 01/2024,Revenue 01/2024,Downloads 02/2024,Revenue 02/2024
0,Genshin Impact,US,"2,800,000","34,000,000","2,900,000","48,000,000","3,000,000","45,000,000","2,700,000","32,000,000",...,2.700.000,"38,000,000","1,700,000","55,000,000","2,700,000","31,000,000","2,700,000","36,000,000","2,600,000","32,000,000"
1,Honkai Star Rail,US,"6,000,000","82,000,000","11,000,000","23,000,000","5,000,000","43,000,000","1,700,000","58,000,000",...,1.400.000,"44,000,000","1,200,000","20,000,000","1,600,000","28,000,000","1,300,000","20,000,000","1,400,00","30,000,000"
2,Honkai Star Rail,CN,"1,000,000","57,000,000","800,000","52,000,000","650,000","46,000,000","500,000","38,000,000",...,"400,000","37,000,000","200,000","11,000,00","300,000","23,000,000","300,000","10,000,000","300,000","22,000,000"
3,Genshin Impact,CN,"600,000","23,000,000","700,000","46,000,000","700,000","44,000,000","700,000","25,000,000",...,"700,000","33,000,000","600,000","44,000,000","110,000","22,000,000","600,000","23,000,000","700,000","21,000,000"
4,Uma Musume,JP,"50,000","27,000,000","50,000","23,000,000","80,000","74,000,000","30,000","22,000,000",...,"30,000","21,000,000","30,000","15,000,000","500,000","20,000,000","40,000","21,000,000","600,000","20,000,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,404,JP,"50,000","600,000","170,000","190,000",NaN,NaN,"10,000","300,000",...,"10,000","160,000","10,000","10,000",0,0,0,0,0,0
80,Sinoalice,JP,"10,000","500,000","10,000","800,000","10,000","800,000","10,000","1,500,000",...,"10,000","140,000","10,000","10,000",0,0,0,0,0,0
81,Sinoalice,US,"10,000","100,000","10,000","160,000","10,000","80,000","10,000","150,000",...,"10,000","10,000",0,0,0,0,0,0,0,0
82,IM@S saisuta,JP,"10,000","25,000","12,000","400,000","10,000","600,000",0,0,...,0,0,0,0,0,0,0,0,0,0
83,LL SIFAS,JP,"10,000","25,000","12,000","400,000","10,000","600,000",0,0,...,0,0,0,0,0,0,0,0,0,0